In [1]:
#######################################################################################################
###################### More functions that are very helpful in Data Analysis ##########################
#######################################################################################################

In [1]:
import numpy as np

In [28]:
#### where(condition)
# extract index of items; not item itself, that satisfy a certain conition
arr = np.array([2,4,6,7,11,9,9,3,3])
ind_4 = np.where(arr > 4) # posisition of items greater than 4
ind_4

(array([2, 3, 4, 5, 6], dtype=int64),)

In [29]:
# Retreive items by an index array
arr.take(ind_4)

array([[ 6,  7, 11,  9,  9]])

In [30]:
# placing values based on the condition
# where(condition, value if True, value if False)
np.where(arr > 4, 'pass', 'fail') 

array(['fail', 'fail', 'pass', 'pass', 'pass', 'pass', 'pass', 'fail',
       'fail'], dtype='<U4')

In [31]:
### index of max and min values
print(np.argmax(arr)); print(np.argmin(arr))

4
0


In [34]:
#### read data from a .csv file
# np.gefromtxt(path, delimiter char, skip_header=True or False, filling_values= value in case of missing values, dtype='int, float, object, str, bool')
# in case of files containing text as well as number, set the dtype='object' or None
data = np.genfromtxt('test.csv', delimiter=',', skip_header=1, filling_values=-999, dtype='float')

In [35]:
data[1]

array([ 1.500e+01,  8.000e+00,  3.500e+02,  1.650e+02,  3.693e+03,
        1.150e+01,  7.000e+01,  1.000e+00, -9.990e+02])

In [36]:
# write data to a .csv file
np.savetxt('output.csv', data, delimiter=',')

PermissionError: [Errno 13] Permission denied: 'output.csv'

In [37]:
### Serilization: saving objects
# save the np array object as .npy, so that you can load it later without re-running the whole script at hand
np.save('savedArr.npy', arr)

#load back
loaded_arr = np.load('savedArr.npy')
loaded_arr

array([ 2,  4,  6,  7, 11,  9,  9,  3,  3])

In [38]:
#### Array Concatenation --- Arrays should be the same size
a = np.zeros([2,2])
b = np.ones([2,2])

In [39]:
# concatenate by row --- 3 
print(np.r_[a,b]);

#print(np.concatenate([a,b], axis=0));
#print(np.vstack([a,b]));

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


In [40]:
# concatenate by col
print(np.c_[a,b]);
#print(np.concatenate([a,b], axis=1));
#print(np.hstack([a,b]));

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [41]:
### Sorting
arr2 = np.random.randint(1,10, size=[3,5])
arr2

array([[9, 6, 6, 4, 2],
       [2, 1, 8, 8, 4],
       [1, 4, 6, 5, 1]])

In [42]:
# sort the whole array
np.sort(arr2)

array([[2, 4, 6, 6, 9],
       [1, 2, 4, 8, 8],
       [1, 1, 4, 5, 6]])

In [44]:
# sort each column
np.sort(arr2, axis=0)

array([[1, 1, 6, 4, 1],
       [2, 4, 6, 5, 2],
       [9, 6, 8, 8, 4]])

In [45]:
#sort each row
np.sort(arr2, axis=1)

array([[2, 4, 6, 6, 9],
       [1, 2, 4, 8, 8],
       [1, 1, 4, 5, 6]])

In [47]:
# sort by first column without distrubing the rows 
# first get the right sort of first col's indices
sorted_col = arr2[:,0].argsort()
sorted_col

array([2, 1, 0], dtype=int64)

In [50]:
# display the array using that sorted column
arr2[sorted_col]

# sort descending 
arr2[sorted_col[::-1]]

array([[9, 6, 6, 4, 2],
       [2, 1, 8, 8, 4],
       [1, 4, 6, 5, 1]])